#!/bin/bash
#Author : Kumar Abhijeet
#Description : This scipt will run basic admin commands
#Date : 21-05-2021
#Date Modified : 21-05-2021

echo
echo This script will run few basic administrative commands
echo
top | head -20
echo
df -h
echo
free -m
echo
uptime
echo
iostat
echo
echo End of script
