#!/bin/bash
# Description : This script shows how case statement works

echo
echo Please chose one of the options below
echo
echo ‘a = Display Date and Time’
echo ‘b = List file and Directories’
echo ‘c = Lists users logged in’
echo ‘d = check system uptime’
 echo
	read choices

	case $choices in
a)	date ;;
b)	ls;;
c)	who;;
d)	uptime;;
*) echo Invalid choice – Bye
	esac

